### PR TITLE
Test parser on Windows.

### PR DESCRIPTION
**Pull request by jendrikseipp**
This is just a test and not meant for merging.

### CODE REVIEW

**Comment by FlorianPommerening** [comment]
Should we pull in #191 here to test if that fixes things?

**Comment by jendrikseipp** [comment]
Good idea. Feel free to play around here.

**Comment by FlorianPommerening** [comment]
I sent a PR to this branch. I don't think I have the rights to merge it.

**Comment by jendrikseipp** [comment]
Merges. Let's see what the CI says.

**Comment by FlorianPommerening** [comment]
Looks ok, should we merge #191 then?

**Comment by jendrikseipp** [comment]
No objections from my side.

**Pull request closed without merging**
