### PR TITLE
Translate: improve error message when files do not start with "(define "

### PR DESCRIPTION
**Pull request by victorpaleologue**

### CODE REVIEW

**Comment by victorpaleologue** [comment]
@maltehelmert This is the PR going along this issue http://issues.fast-downward.org/issue1029

**Comment by Toover** [comment]
I loved to meet you at ICAPS 2022!
I hope you don't mind I bump this PR.

**Comment by victorpaleologue** [comment]
I loved to meet you at ICAPS 2022!
I hope you don't mind I bump this PR.

**Comment by victorpaleologue** [comment]
@FlorianPommerening who would you recommend me to ping with this?

**Comment by FlorianPommerening** [comment]
Hi @victorpaleologue, I'd normally suggest to use the tracker for pinging but this works as well. We would prefer to improve error reporting in a more general way, rather than fixing assertion messages that are not meant for error reporting. We have this on our list to look into at our next sprint in January and if we can make some progress there, this should also cover reporting a missing "(define". If we don't manage to merge something larger by February, we can merge this diff as a stopgap so it doesn't stay open forever.

**Comment by FlorianPommerening** [comment]
The notification email from the tracker bounced. Can you check that your email address there is up to date?

**Comment by maltehelmert** [comment]
Superseded by #155, so I'm closing this. But thank you for bringing this to our attention! This was what ultimately triggered the more extensive rewrite of the PDDL parser.

**Pull request closed without merging**
